name: Build & Deploy Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system libs
        run: sudo apt-get update && sudo apt-get install libvips-dev -y

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Config npm registry
        run: npm config set registry https://registry.npmmirror.com

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: UniApp Build H5
        run: npm run build:h5

      - name: List build output
        run: ls -la ./dist/build/h5

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/build/h5
          force_orphan: true
